Make initscripts pass shellcheck
- make scripts fail and abort the entrypoint on errors and undefined
  variables
- consistency in sed parameter order

diff --git a/containers/server-image/root/docker-entrypoint-init b/containers/server-image/root/docker-entrypoint-init
--- a/containers/server-image/root/docker-entrypoint-init
+++ b/containers/server-image/root/docker-entrypoint-init
@@ -1,8 +1,10 @@
 #!/usr/bin/bash
+# Fail is any init script fails
+set -e
 
-for f in `ls /docker-entrypoint-init.d/*.sh | sort`; do
+for f in $(find /docker-entrypoint-init.d/ -type f -name  '*.sh' | sort); do
     echo "Executing $f..."
-    bash $f
+    bash "$f"
 done
 
 # This needs to be last for systemd to become PID1
